### PR TITLE
Callback function for RPDO which are not synchronous

### PR DESCRIPTION
**Pull request by sandrogort**
First some context. I tried to make an example for sync communication in which a sync producer and a sync consumer node are involved. The documentation can be found here [README.md](https://github.com/sandrogort/canopen-linux/blob/main/src/apps/setpoint/README.md). Upon receiving a PDO, there is only a RPDO callback (COPdoSyncUpdate) for synchronous communication but none for assynchronous. This example is inspired by the Lely CANopen stack tutorial [tutorial](https://opensource.lely.com/canopen/docs/cpp-tutorial/).

What I want is a callback also when the RPDO is written asynchronously. For that purpose a callback called COPdoAsyncUpdate was introduced. If I did reinvent the wheel here please let me know.

From an API perspective I am not sure if this ideal. The Lely stack provides a OnRpdoWrite callback independent of sync or async method which might be sufficient for most use cases.

### CODE REVIEW

**Comment by michael-hillmann** [comment]
Sorry for the long delay and thank you for your collaboration!
Could you change the merge branch to embedded-office:develop, please?
This way I can merge it for the upcoming version v4.4.1 or v4.5.0 with you as author.

**Comment by sandrogort** [comment]
The merge branch is set to develop now.

**Comment by michael-hillmann** [comment]
Ok, great. Do you think it is useful to distinguish between sync and async updates? I'm not sure, because this is a setting in the PDO communication params. Maybe we should join the two callbacks into a single one `COPdoUpdate()`? Simplifies the usage when dynamic PDO communication takes place.

What do you think?

**Comment by sandrogort** [comment]
I think it makes sense to join them, but obviously would lead to a minor breaking change in the API. I assume normally a user would not want to know if the callback is sync or async and with the object definition it can even be found out if it was written in sync or async context. Furthermore, I checked the Lely stack and they provide a OnRpdoWrite() callback which I assume would be called in sync and async context.
I will change the merge request accordingly and also change the documentation if this is fine for you?

**Comment by michael-hillmann** [comment]
Yes, I agree. We can leave the old callback COPdoSyncUpdate() for some time and declare it as "deprecated" in the docs. For new or updating users, the COPdoUpdate() callback should be prefered.

**Comment by sandrogort** [comment]
I messed up this pull request due to branching of off master instead of develop. I opened a new pull request for the agreed change. See [Callback function for both synchronous and asynchronous RPDO write #145](https://github.com/embedded-office/canopen-stack/pull/145). This pull request should be closed without merging.

**Comment by michael-hillmann** [comment]
Ok, PR #145 is merged. Closing this one.

**Pull request closed without merging**
